import type { AppShellWiring } from "./useAppShellWiring";

export type AppShellRoutesProps = Pick<
  AppShellWiring,
  | "activeTab"
  | "sessionState"
  | "library"
  | "downloadQueue"
  | "music"
  | "audiobook"
  | "downloads"
  | "currentTrack"
  | "isPlaying"
  | "positionMs"
  | "miniTitle"
  | "miniSubtitle"
  | "savedBookProgress"
  | "bookIsListened"
  | "openBook"
  | "deleteDownload"
  | "triggerSync"
  | "handleLogout"
  | "showSignOutConfirm"
  | "setShowSignOutConfirm"
  | "showSyncDialog"
  | "setShowSyncDialog"
  | "syncing"
  | "setSyncing"
  | "refreshSession"
  | "displayName"
  | "userEmail"
  | "avatarUrl"
  | "memberSinceEpochMs"
  | "error"
>;
